//
//  CourseListModels.swift
//  SwiftBookAppPatterns
//
//  Created by Vladimir Stepanchikov on 15.02.2021.
//  Copyright (c) 2021 Vladimir Stepanchikov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

typealias CourseDisplayedFields = CourseList.ShowCourses.Response.CourseDisplayedFields

enum CourseList {
    
    // MARK: Use cases
    enum ShowCourses {
        struct Response {
            struct CourseDisplayedFields {
                let courseName: String
                let imageData: Data?
            }
            let courseList: [CourseDisplayedFields]
            
        }
        
        struct ViewModel {
            let courseList: [CourseDisplayedFields]
        }
    }
}

