//
//  CourseListInteractor.swift
//  SwiftBookAppPatterns
//
//  Created by Vladimir Stepanchikov on 15.02.2021.
//  Copyright (c) 2021 Vladimir Stepanchikov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseListBusinessLogic {
    func showCourses()
}

protocol CourseListDataStore {
    var courses: [Course] { get }
}

class CourseListInteractor: CourseListBusinessLogic, CourseListDataStore {
    // MARK: - Public Properties
    var presenter: CourseListPresentationLogic?
    var worker: CourseListWorker?
    
    var courses: [Course] = []
    
    // MARK: - Public Methods
    func showCourses() {
        worker = CourseListWorker()
        
        NetworkManager.shared.fetchData { [weak self] courses in
            guard let self = self else { return }
            self.courses = courses
            guard let courseList = self.worker?.getCourseList(from: courses) else { return }
            
            let response = CourseList.ShowCourses.Response(courseList: courseList)
            self.presenter?.presentCourses(response: response)
        }
    }
}
