//
//  CourseDetailsInteractor.swift
//  SwiftBookAppPatterns
//
//  Created by Vladimir Stepanchikov on 15.02.2021.
//  Copyright (c) 2021 Vladimir Stepanchikov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsBusinessLogic {
    var isFavorite: Bool { get }
    func showDetails(request: CourseDetails.ShowDetails.Request)
    func setFavoriteStatus()
}

protocol CourseDetailsDataStore {
    var course: Course? { get set }
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    // MARK: - Public Properties
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    var course: Course?
    var isFavorite = false
    
    // MARK: Public Methods
    func showDetails(request: CourseDetails.ShowDetails.Request) {
        worker = CourseDetailsWorker()
        isFavorite = worker?.getFavoriteStatus(for: course?.name ?? "") ?? false
        
        let response = CourseDetails.ShowDetails.Response(
            courseName: course?.name ?? "",
            numberOfLessons: course?.numberOfLessons ?? 0,
            numberOfTests: course?.numberOfTests ?? 0,
            imageData: worker?.fetchImage(from: course?.imageUrl),
            isFavorite: isFavorite
        )
        
        presenter?.presentCourseDetails(response: response)
    }
    
    func setFavoriteStatus() {
        isFavorite.toggle()
        worker?.setNewFavoriteStatus(for: course?.name ?? "", with: isFavorite)
        
        let response = CourseDetails.SetFavoriteStatus.Response(isFavorite: isFavorite)
        presenter?.presentFavoriteStatus(response: response)
    }
}
