//
//  CourseDetailsPresenter.swift
//  SwiftBookAppPatterns
//
//  Created by Vladimir Stepanchikov on 15.02.2021.
//  Copyright (c) 2021 Vladimir Stepanchikov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsPresentationLogic {
    func presentCourseDetails(response: CourseDetails.ShowDetails.Response)
    func presentFavoriteStatus(response: CourseDetails.SetFavoriteStatus.Response)
}

class CourseDetailsPresenter: CourseDetailsPresentationLogic {
    
    weak var viewController: CourseDetailsDisplayLogic?
    
    func presentCourseDetails(response: CourseDetails.ShowDetails.Response) {
        let viewModel = CourseDetails.ShowDetails.ViewModel(
            courseName: response.courseName ?? "",
            numberOfLessons: "Number of lessons: \(response.numberOfLessons ?? 0)",
            numberOfTests: "Number of tests: \(response.numberOfTests ?? 0)",
            imageData: response.imageData,
            isFavorite: response.isFavorite
        )
        
        viewController?.displayCourseDetails(viewModel: viewModel)
    }
    
    func presentFavoriteStatus(response: CourseDetails.SetFavoriteStatus.Response) {
        let viewModel = CourseDetails.SetFavoriteStatus.ViewModel(
            isFavorite: response.isFavorite
        )
        
        viewController?.displayImageForFavoriteButton(viewModel: viewModel)
    }
}
